# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GSC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GSC
pod 'MaterialComponents'
pod 'Alamofire'
  target 'GSCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GSCUITests' do
    # Pods for testing
  end

end
